### ISSUE TITLE
Install on ABT Node 可以升级为让钱包来决定用哪个node, 而不是靠local storage. 

### ISSUE THREAD

**Issue by mave99a** [blocklet/blocklet-launcher#19]
Install on ABT Node 可以升级为让钱包来决定用哪个node, 而不是靠local storage. 

我们仍然需要install on abt node 来跳转， 但不同的是，我们不再依赖于local storage, 而是让钱包扫码来授权选择让某个ABT Node来安装blocklet

ABT Node里的register on install-on-abtnode将不再有必要，可以删除

相关：
https://github.com/blocklet/abt-node-launcher/issues/97

**Comment by mave99a** [comment]
这个如果能实现的比较理想会很有价值，并且可以和钱包中的abt node列表配合。 

思考： 
- 这里的列表和钱包里知道可以访问的列表是什么关系？
- web上的列表如何获得和更新 （不依赖local storage后必需靠钱包提供， 如何提供？）

**Comment by mave99a** [comment]
@dosthcool  再结合思考下最早试图设计的 DID Profile / DID Home. 

用户有哪些node可以管理，也可以认为是用户自己的profile / home的一部分

https://docs.google.com/document/d/11A5sz-Viu3vbEGWj7-3mNnKWHIJnW4mWaome1Eki5_0/edit

**Comment by dosthcool** [comment]
DID Profile / DID Home 和 Install on ABT Node的关系是？

**Comment by mave99a** [comment]
> DID Profile / DID Home 和 Install on ABT Node的关系是？

我感觉 install on ABT Node是 DID Home里的一个功能/工具的感觉。 

你的home 里 有你所有的 abt node,  因此你有个工具专门负责来安装到自己的这些 abt node上去。 

DID Home 相当于是 cloud agent这种概念，和钱包是相辅相成的 （钱包是edge/device agent). 

![image](https://user-images.githubusercontent.com/41923/133725540-a5b1aacc-4b5f-424b-86d8-067ffa169a25.png)

这篇文章：
https://freecontent.manning.com/the-basic-building-blocks-of-ssi/

**Comment by mave99a** [comment]
好像已经支持了， @polunzh 看是不是这个issue可以close

**Comment by mave99a** [comment]
如果上文讨论还有用，也可以保留track

**Comment by polunzh** [comment]
> 如果上文讨论还有用，也可以保留track

issue 本身可以关掉了，如果后面有新的设计想法可以再单开 issue.
