### ISSUE TITLE
abtnode dev .  和  abtnode deploy . 运行无效

### ISSUE THREAD

**Issue by kirakiray** [blocklet/blocklet-launcher#31]
会出现不存在以下指令的问题：

error: unknown command 'dev'. See 'abtnode --help'.

error: unknown command 'deploy'. See 'abtnode --help'.

abtnode --version 
1.5.11

**Comment by wangshijun** [comment]
@kirakiray 你在哪里看到这两个命名的入口的？这两个命令都应该在 blocklet 命令行下面。

**Comment by kirakiray** [comment]
> @kirakiray 你在哪里看到这两个命名的入口的？这两个命令都应该在 blocklet 命令行下面。

https://github.com/blocklet/blocklet-launcher

入口这里的教程，下面的地方；

是不是勘误？是的话让我试试提交修改；

**Comment by kirakiray** [comment]
已将相关指令更新为 `blocklet`
