### ISSUE TITLE
update "Install on ABT Node" to "Launch Blocklet"

### ISSUE THREAD

**Issue by mave99a** [blocklet/blocklet-launcher#32]
update 各个blocklet repo里这个button：

![](https://raw.githubusercontent.com/blocklet/development-guide/main/assets/install_on_abtnode.svg)

文字改为launch blocklet

图案最好能设计一下，让这个按钮一看就能知道是我们平台的， 因此应该在图案和色彩上和blocklet 系列配套。

和blocklet store这里的按钮可能应该统一风格，这样用户形成完成的品牌感觉

<img width="464" alt="image" src="https://user-images.githubusercontent.com/41923/144770408-ff9fe1bd-133c-44ad-ae71-66575320b076.png">

这个launch 按钮可以有图标、文字、大、小一个系列

**Comment by dosthcool** [comment]
设计讨论过程：https://github.com/ArcBlock/design/discussions/75

**Comment by polunzh** [comment]
![image](https://user-images.githubusercontent.com/4244426/149900925-a08343d7-b078-4daf-b44f-dedc801c0029.png)
